# <?= $this->className ?>


<?php
    if ($this->classDescription->short) {
        echo "{$this->classDescription->short}  \n";
    }
    if ($this->classDescription->long) {
        echo str_replace("\n", "  \n", $this->classDescription->long);
    }
?>


<?php if ($this->classDescription->long) : ?>

<?= $this->classDescription->long ?>
<?php endif ?>

<?php if ($interfaces = $this->interfaces): ?>
## 接口:
<?= join(', ', $interfaces); ?>
<?php endif ?>


<?php if ($this->parentClass): ?>
## 父类:

<?= $this->parentClass ?>
<?php endif ?>


<?php if (count($this->methods) > 0): ?>
## 方法

| 名称 | 说明 |
|------|------|
<?php foreach ($this->methods as $name => $info) : ?>
|[<?= $name ?>](#<?= strtolower($this->classShortName.$name) ?>)|<?= $info->shortDescription ?>|
<?php endforeach ?>
<?php endif ?>


<?php if ($this->inheritedMethods): ?>
## 继承的方法

| 名称 | 说明 |
|------|------|
<?php foreach ($this->inheritedMethods as $name => $info) : ?>
|<?= $name ?>|<?= $info->shortDescription ?: '-' ?>|
<?php endforeach ?>
<?php endif ?>


<?php foreach ($this->methods as $name => $info) : ?>

### <?= $this->classShortName ?>::<?= $name ?>

#### 描述

```php
<?= $info->visibility ?> <?= $name ?> (<?= join(', ', $info->argumentsList) ?: 'void' ?>)
```

<?= $info->shortDescription . '  ' ?>

<?= str_replace("\n", "  \n", $info->longDescription) ?>


<?php if ($info->argumentsDescription): ?>
#### 参数

<?php foreach ($info->argumentsDescription as $param) : ?>
* **(<?= join('|', $param->type) ?>)** <?= $param->name ?>
<?php if ($param->desc) : ?>
: <?php
    if (strpos($param->desc, '```') === 0) {
        echo "\n" . $param->desc;
    } else if (strpos($param->desc, '```') !== false) {
        echo $param->desc;
    } else {
        echo str_replace("\n", "  \n", $param->desc);
    }
?>
<?php endif ?>

<?php endforeach ?>
<?php endif ?>


<?php if (count($info->returnValue) > 0): ?>
#### 返回值

<?php foreach ($info->returnValue as $param) : ?>
**(<?= join('|', $param->type) ?>)** <?php
if (strpos($param->desc, '```') === 0) {
    echo "\n" . $param->desc;
} else if (strpos($param->desc, '```') !== false) {
    echo $param->desc;
} else {
    echo str_replace("\n", "  \n", $param->desc);
}
?>

<?php endforeach ?>
<?php endif ?>


<?php endforeach ?>
